:showtitle:
:page-title: SVG 1.1 Full Static Support

:ok-box: pass:[image:images/passed.svg[20,20, title="Passed"]]
:fail-box: pass:[image:images/failed.svg[20,20, title="Failed"]]
:part-box: pass:[image:images/partial.svg[20,20, title="Partial"]]
:unk-box: pass:[image:images/unknown.svg[20,20, title="Unknown"]]
:crash-box: pass:[image:images/crashed.svg[20,20, title="Crashed"]]
:oos-box: pass:[image:images/out-of-scope.svg[20,20, title="Out of scope"]]

= SVG 1.1 Full Static Support
:toc:
:toc-title:

== About

This page contains results of the https://github.com/RazrFalcon/resvg-test-suite[resvg test suite]
which is specifically designed for the https://github.com/RazrFalcon/resvg[resvg] library.


=== Test suite design

* One file - one test. +
  In the official test suite, one file can have a lot of tests.
* More edge-cases. +
  Unlike the official https://www.w3.org/Graphics/SVG/Test/20110816/[SVG test suite].
* Only supported SVG subset. +
  `resvg` trying to support only the https://www.w3.org/TR/SVG11/feature#SVG-static[static] SVG subset.
* Tests are grouped by the element and attribute names.
* No raster images as references. +
  We are using https://github.com/RazrFalcon/resvg-test-suite/tree/master/tools/vdiff[vdiff] tool to check that tests are passed.

=== What we don't test

* Features that isn't yet implemented in the `resvg`.
* XML parsing. +
  Except some DTD and namespace resolving we assume that SVG library supports full XML 1.0 spec.
* Extended CSS support. +
  In the `resvg` case CSS parsing is done on the https://github.com/RazrFalcon/libsvgdom[svgdom] side.
  And we support only a minimal CSS subset.
* Extended raster image formats features. +
  We assume that underlying PNG and JPEG libraries are good.
* `a` element. We treating it as `g`.
* Pointer events.
* Animations.
* Scripting.
* Embedded fonts.

=== Other SVG libraries and applications

We are testing/comparing `resvg` with Chrome, Inkscape, librsvg and QtSvg for a reason.

* Chrome has the best SVG support and used as a reference implementation.
* Inkscape is an obvious choice on Linux.
* librsvg is the main `resvg` rival. Used in GNOME, XFCE for SVG rendering.
  The goal is to replace `librsvg` with `resvg`.
* QtSvg is used by all the Qt applications and KDE. We plan to replace it as well.

=== Tests summary

image:images/chart.svg[]

=== Legend

[cols="^1,3,^1,3", width="40%"]
|===
| {ok-box}   | Passed  | {unk-box}   | Unknown
| {fail-box} | Failed  | {crash-box} | Crashed
| {part-box} | Partial | {oos-box}   | Out of scope
|===

Rows like this indicate that such element/attribute is planned but not yet implemented.

[cols="1,10,^1,^1,^1,^1,^1"]
|===
2+| name ^|{fail-box}|{unk-box}|{unk-box}|{unk-box}|{unk-box}
|===

== Elements

include::elements-table.adoc[]

== Attributes

=== Presentation

include::presentation-attributes-table.adoc[]

=== Other

include::attributes-table.adoc[]

== Tests

:3H: ###

Test files can be found https://github.com/RazrFalcon/resvg-test-suite/tree/master/svg[here].

Naming convention: `type`-`name`-`{3H}`.svg

`type` can be either `a`(attribute) or `e`(element).

For example the _polyline - 3. Ignore odd points_ will lead to `e-polyline-003.svg`.
